In [4]:
# Link To Grab data
#https://www.espncricinfo.com/records/highest-career-batting-average-282910

# grab data from website and export to m.excel
# convert file into csv file

In [5]:
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Users\User\OneDrive\Desktop\Data Analyst\Cricket Test Match data\CricketTestMatchData.csv")
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [8]:
pd.set_option('display.max_rows',70)

In [9]:
# rename multiple Columns in a list   --- using dictionaries
df = df.rename(columns = {'Mat': 'Matches', 'NO':'Not_Outs', 'HS': 'Highest_Inns_Score', 'BF': 'Balls_Faced', 'SR': 'Battling_Strike_Rate' })

In [10]:
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1

In [11]:
# Checking Null values
df.isnull().any()

Player                  False
Span                    False
Matches                 False
Inns                    False
Not_Outs                False
Runs                    False
Highest_Inns_Score      False
Ave                     False
Balls_Faced              True
Battling_Strike_Rate     True
100                     False
50                      False
0                       False
4s                      False
6s                      False
dtype: bool

In [12]:
# investigating the Null Values in specific column
df[df['Balls_Faced'].isna()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258,2
16,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107,11
57,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,NaN,NaN,5,6,3,51,0

In [15]:
# replace the null values with 0
df["Balls_Faced"] = df["Balls_Faced"].fillna(0)

In [16]:
#Checking the replaced values
df[df["Player"]=="ED Weekes (WI)"]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,NaN,15,19,6,258,2

In [17]:
df[df["Battling_Strike_Rate"].isna()== 1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,NaN,15,19,6,258,2
16,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,NaN,15,14,1,107,11
57,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,0,NaN,5,6,3,51,0

In [18]:
df["Battling_Strike_Rate"] = df["Battling_Strike_Rate"].fillna(0)

In [19]:
df[df["Player"]=="ED Weekes (WI)"]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.0,15,19,6,258,2

In [20]:
#selecting multiple rows base on Column name
df[df["Player"].isin(["ED Weekes (WI)","CL Walcott (WI)","Hon.FS Jackson (ENG)"])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.0,15,19,6,258,2
16,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.0,15,14,1,107,11
57,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,0,0.0,5,6,3,51,0

In [21]:
#checking duplicates
df.duplicated().any()

True

In [22]:
# investigating duplicated data base on rows
df[df["Player"].duplicated()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
53,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [23]:
df[df["Player"].isin(["GS Sobers (WI)","JB Hobbs (ENG)","V Kohli (IND)"])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
11,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
15,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8
52,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26
53,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26

In [24]:
# dropping duplicates
df = df.drop_duplicates()
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1

In [23]:
# Split up Span into Start and End Date + career Length
df["Span"].str.split(pat = "-",expand = True)

       0     1
0   1928  1948
1   2022  2023
2   2015  2016
3   1963  1970
4   1930  1954
5   1924  1935
6   1931  1939
7   1955  1968
8   1948  1958
9   1927  1947
10  1954  1974
11  1954  1974
12  2000  2015
13  2010  2024
14  1908  1930
15  1908  1930
16  1948  1960
17  1937  1955
18  1995  2013
19  1921  1929
20  2010  2024
21  1968  1973
22  1993  1995
23  1970  1984
24  1935  1951
25  1989  2013
26  1990  2006
27  1976  1993
28  1996  2012
29  1998  2010
30  2000  2017
31  1995  2012
32  1920  1929
33  1992  2002
34  2005  2013
35  1994  2015
36  1971  1987
37  1985  2004
38  1994  2009
39  2004  2018
40  1978  1994
41  2019  2024
42  1974  1991
43  1937  1957
44  1997  2014
45  2012  2024
46  1992  2007
47  2018  2024
48  1948  1963
49  1911  1928
50  2001  2013
51  2019  2021
52  2011  2024
53  2011  2024
54  2004  2015
55  1961  1966
56  1929  1949
57  1893  1905
58  2001  2013
59  1948  1963
60  1965  1981
61  2002  2014
62  1924  1934
63  1930  1938
64  1928  1934

In [25]:
df[["Rookie_Year","Final_Year"]] = df["Span"].str.split("-",expand=True)

In [26]:
df

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948
1,HC Brook (ENG),2022-2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6,1924,1935
6,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4,1931,1939
7,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27,1955,1968
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958
9,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27,1927,1947
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974
12,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015
13,SPD Smith (AUS),2010-2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930
16,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960
17,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7,1937,1955
18,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2,1921,1929
20,KS Williamson (NZ),2010-2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024
21,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1,1968,1973
22,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
23,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
24,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6,1935,1951
25,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69,1989,2013
26,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
27,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48,1976,1993
28,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
29,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
30,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
31,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
32,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3,1920,1929
33,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
34,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
35,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
36,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26,1971,1987
37,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
38,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
39,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
40,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
41,DJ Mitchell (NZ),2019-2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024
42,IVA Richards (WI),1974-1991,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84,1974,1991
43,DCS Compton (ENG),1937-1957,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3,1937,1957
44,DPMD Jayawardene (SL),1997-2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
45,JE Root (ENG),2012-2024,140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024
46,Inzamam-ul-Haq (ICC/PAK),1992-2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
47,M Labuschagne (AUS),2018-2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
48,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11,1948,1963
49,CP Mead (ENG),1911-1928,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0,1911,1928
50,V Sehwag (ICC/IND),2001-2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
51,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
52,V Kohli (IND),2011-2024,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
54,MJ Clarke (AUS),2004-2015,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015
55,KC Bland (SA),1961-1966,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20,1961,1966
56,B Mitchell (SA),1929-1949,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1,1929,1949
57,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144*,48.79,0,0.00,5,6,3,51,0,1893,1905
58,TT Samaraweera (SL),2001-2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
59,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1,1948,1963
60,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981
61,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
62,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934
63,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938
64,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934

In [27]:
# Dropping unusable columns
df = df.drop(["Span"],axis =1)

In [27]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6,1924,1935
6,E Paynter (ENG),20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4,1931,1939
7,KF Barrington (ENG),82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27,1955,1968
8,ED Weekes (WI),48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958
9,WR Hammond (ENG),85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27,1927,1947
10,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974
11,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974
12,KC Sangakkara (SL),134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015
13,SPD Smith (AUS),109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024
14,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930
15,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930
16,CL Walcott (WI),44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960
17,L Hutton (ENG),79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7,1937,1955
18,JH Kallis (ICC/SA),166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013
19,GE Tyldesley (ENG),14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2,1921,1929
20,KS Williamson (NZ),100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024
21,CA Davis (WI),15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1,1968,1973
22,VG Kambli (IND),17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995
23,GS Chappell (AUS),87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984
24,AD Nourse (SA),34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6,1935,1951
25,SR Tendulkar (IND),200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69,1989,2013
26,BC Lara (ICC/WI),131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006
27,Javed Miandad (PAK),124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48,1976,1993
28,R Dravid (ICC/IND),164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012
29,Mohammad Yousuf (PAK),90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010
30,Younis Khan (PAK),118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017
31,RT Ponting (AUS),168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012
32,J Ryder (AUS),20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3,1920,1929
33,A Flower (ZIM),63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002
34,MEK Hussey (AUS),79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013
35,S Chanderpaul (WI),164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015
36,SM Gavaskar (IND),125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26,1971,1987
37,SR Waugh (AUS),168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004
38,ML Hayden (AUS),103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009
39,AB de Villiers (SA),114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018
40,AR Border (AUS),156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994
41,DJ Mitchell (NZ),23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024
42,IVA Richards (WI),121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84,1974,1991
43,DCS Compton (ENG),78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3,1937,1957
44,DPMD Jayawardene (SL),149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014
45,JE Root (ENG),140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024
46,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007
47,M Labuschagne (AUS),50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024
48,FMM Worrell (WI),51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11,1948,1963
49,CP Mead (ENG),17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0,1911,1928
50,V Sehwag (ICC/IND),104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013
51,Abid Ali (PAK),16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021
52,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
53,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024
54,MJ Clarke (AUS),115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015
55,KC Bland (SA),21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20,1961,1966
56,B Mitchell (SA),42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1,1929,1949
57,Hon.FS Jackson (ENG),20,33,4,1415,144*,48.79,0,0.00,5,6,3,51,0,1893,1905
58,TT Samaraweera (SL),81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013
59,RN Harvey (AUS),79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1,1948,1963
60,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981
61,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
62,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934
63,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938
64,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934

In [28]:
# Question -> Split up the Country from the player

df["Player"].str.split(pat ="(" ,expand = True)

                    0         1
0         DG Bradman       AUS)
1           HC Brook       ENG)
2           AC Voges       AUS)
3         RG Pollock        SA)
4         GA Headley        WI)
5        H Sutcliffe       ENG)
6          E Paynter       ENG)
7      KF Barrington       ENG)
8          ED Weekes        WI)
9         WR Hammond       ENG)
10         GS Sobers        WI)
12     KC Sangakkara        SL)
13         SPD Smith       AUS)
14          JB Hobbs       ENG)
16        CL Walcott        WI)
17          L Hutton       ENG)
18         JH Kallis    ICC/SA)
19      GE Tyldesley       ENG)
20     KS Williamson        NZ)
21          CA Davis        WI)
22         VG Kambli       IND)
23       GS Chappell       AUS)
24         AD Nourse        SA)
25      SR Tendulkar       IND)
26           BC Lara    ICC/WI)
27     Javed Miandad       PAK)
28          R Dravid   ICC/IND)
29   Mohammad Yousuf       PAK)
30       Younis Khan       PAK)
31        RT Ponting       AUS)
32           J Ryder       AUS)
33          A Flower       ZIM)
34        MEK Hussey       AUS)
35     S Chanderpaul        WI)
36       SM Gavaskar       IND)
37          SR Waugh       AUS)
38         ML Hayden       AUS)
39    AB de Villiers        SA)
40         AR Border       AUS)
41       DJ Mitchell        NZ)
42      IVA Richards        WI)
43       DCS Compton       ENG)
44  DPMD Jayawardene        SL)
45           JE Root       ENG)
46    Inzamam-ul-Haq   ICC/PAK)
47     M Labuschagne       AUS)
48       FMM Worrell        WI)
49           CP Mead       ENG)
50          V Sehwag   ICC/IND)
51          Abid Ali       PAK)
52           V Kohli       IND)
54         MJ Clarke       AUS)
55          KC Bland        SA)
56        B Mitchell        SA)
57    Hon.FS Jackson       ENG)
58    TT Samaraweera        SL)
59         RN Harvey       AUS)
60        KD Walters       AUS)
61          GC Smith    ICC/SA)
62       WH Ponsford       AUS)
63         SJ McCabe       AUS)
64        DR Jardine       ENG)

In [28]:
df["Player"].str.split(pat = "(")

0             [DG Bradman , AUS)]
1               [HC Brook , ENG)]
2               [AC Voges , AUS)]
3              [RG Pollock , SA)]
4              [GA Headley , WI)]
5            [H Sutcliffe , ENG)]
6              [E Paynter , ENG)]
7          [KF Barrington , ENG)]
8               [ED Weekes , WI)]
9             [WR Hammond , ENG)]
10              [GS Sobers , WI)]
11              [GS Sobers , WI)]
12          [KC Sangakkara , SL)]
13             [SPD Smith , AUS)]
14              [JB Hobbs , ENG)]
15              [JB Hobbs , ENG)]
16             [CL Walcott , WI)]
17              [L Hutton , ENG)]
18          [JH Kallis , ICC/SA)]
19          [GE Tyldesley , ENG)]
20          [KS Williamson , NZ)]
21               [CA Davis , WI)]
22             [VG Kambli , IND)]
23           [GS Chappell , AUS)]
24              [AD Nourse , SA)]
25          [SR Tendulkar , IND)]
26            [BC Lara , ICC/WI)]
27         [Javed Miandad , PAK)]
28          [R Dravid , ICC/IND)]
29       [Mohammad Yousuf , PAK)]
30           [Younis Khan , PAK)]
31            [RT Ponting , AUS)]
32               [J Ryder , AUS)]
33              [A Flower , ZIM)]
34            [MEK Hussey , AUS)]
35          [S Chanderpaul , WI)]
36           [SM Gavaskar , IND)]
37              [SR Waugh , AUS)]
38             [ML Hayden , AUS)]
39         [AB de Villiers , SA)]
40             [AR Border , AUS)]
41            [DJ Mitchell , NZ)]
42           [IVA Richards , WI)]
43           [DCS Compton , ENG)]
44       [DPMD Jayawardene , SL)]
45               [JE Root , ENG)]
46    [Inzamam-ul-Haq , ICC/PAK)]
47         [M Labuschagne , AUS)]
48            [FMM Worrell , WI)]
49               [CP Mead , ENG)]
50          [V Sehwag , ICC/IND)]
51              [Abid Ali , PAK)]
52               [V Kohli , IND)]
53               [V Kohli , IND)]
54             [MJ Clarke , AUS)]
55               [KC Bland , SA)]
56             [B Mitchell , SA)]
57        [Hon.FS Jackson , ENG)]
58         [TT Samaraweera , SL)]
59             [RN Harvey , AUS)]
60            [KD Walters , AUS)]
61           [GC Smith , ICC/SA)]
62           [WH Ponsford , AUS)]
63             [SJ McCabe , AUS)]
64            [DR Jardine , ENG)]
Name: Player, dtype: object

In [29]:
df["Player_Name"] = df["Player"].str.split(pat = "(").str[0]

In [30]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Player_Name
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,DG Bradman
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,HC Brook
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,RG Pollock
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954,GA Headley
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6,1924,1935,H Sutcliffe
6,E Paynter (ENG),20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4,1931,1939,E Paynter
7,KF Barrington (ENG),82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27,1955,1968,KF Barrington
8,ED Weekes (WI),48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,ED Weekes
9,WR Hammond (ENG),85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27,1927,1947,WR Hammond
10,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974,GS Sobers
11,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974,GS Sobers
12,KC Sangakkara (SL),134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara
13,SPD Smith (AUS),109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith
14,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930,JB Hobbs
15,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930,JB Hobbs
16,CL Walcott (WI),44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,CL Walcott
17,L Hutton (ENG),79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7,1937,1955,L Hutton
18,JH Kallis (ICC/SA),166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis
19,GE Tyldesley (ENG),14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2,1921,1929,GE Tyldesley
20,KS Williamson (NZ),100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,KS Williamson
21,CA Davis (WI),15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1,1968,1973,CA Davis
22,VG Kambli (IND),17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli
23,GS Chappell (AUS),87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell
24,AD Nourse (SA),34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6,1935,1951,AD Nourse
25,SR Tendulkar (IND),200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69,1989,2013,SR Tendulkar
26,BC Lara (ICC/WI),131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara
27,Javed Miandad (PAK),124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48,1976,1993,Javed Miandad
28,R Dravid (ICC/IND),164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid
29,Mohammad Yousuf (PAK),90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf
30,Younis Khan (PAK),118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan
31,RT Ponting (AUS),168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting
32,J Ryder (AUS),20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3,1920,1929,J Ryder
33,A Flower (ZIM),63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower
34,MEK Hussey (AUS),79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey
35,S Chanderpaul (WI),164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul
36,SM Gavaskar (IND),125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26,1971,1987,SM Gavaskar
37,SR Waugh (AUS),168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh
38,ML Hayden (AUS),103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden
39,AB de Villiers (SA),114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers
40,AR Border (AUS),156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border
41,DJ Mitchell (NZ),23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,DJ Mitchell
42,IVA Richards (WI),121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84,1974,1991,IVA Richards
43,DCS Compton (ENG),78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3,1937,1957,DCS Compton
44,DPMD Jayawardene (SL),149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene
45,JE Root (ENG),140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024,JE Root
46,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq
47,M Labuschagne (AUS),50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne
48,FMM Worrell (WI),51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11,1948,1963,FMM Worrell
49,CP Mead (ENG),17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0,1911,1928,CP Mead
50,V Sehwag (ICC/IND),104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag
51,Abid Ali (PAK),16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali
52,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024,V Kohli
53,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024,V Kohli
54,MJ Clarke (AUS),115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke
55,KC Bland (SA),21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20,1961,1966,KC Bland
56,B Mitchell (SA),42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1,1929,1949,B Mitchell
57,Hon.FS Jackson (ENG),20,33,4,1415,144*,48.79,0,0.00,5,6,3,51,0,1893,1905,Hon.FS Jackson
58,TT Samaraweera (SL),81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera
59,RN Harvey (AUS),79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1,1948,1963,RN Harvey
60,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981,KD Walters
61,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith
62,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,WH Ponsford
63,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,SJ McCabe
64,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,DR Jardine

In [32]:
df["Country"] = df["Player"].str.split(pat = "(").str[1]

In [33]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Player_Name,Country
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,DG Bradman,AUS)
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,HC Brook,ENG)
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS)
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,RG Pollock,SA)
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954,GA Headley,WI)
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6,1924,1935,H Sutcliffe,ENG)
6,E Paynter (ENG),20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4,1931,1939,E Paynter,ENG)
7,KF Barrington (ENG),82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27,1955,1968,KF Barrington,ENG)
8,ED Weekes (WI),48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,ED Weekes,WI)
9,WR Hammond (ENG),85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27,1927,1947,WR Hammond,ENG)
10,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974,GS Sobers,WI)
12,KC Sangakkara (SL),134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara,SL)
13,SPD Smith (AUS),109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith,AUS)
14,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930,JB Hobbs,ENG)
16,CL Walcott (WI),44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,CL Walcott,WI)
17,L Hutton (ENG),79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7,1937,1955,L Hutton,ENG)
18,JH Kallis (ICC/SA),166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis,ICC/SA)
19,GE Tyldesley (ENG),14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2,1921,1929,GE Tyldesley,ENG)
20,KS Williamson (NZ),100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,KS Williamson,NZ)
21,CA Davis (WI),15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1,1968,1973,CA Davis,WI)
22,VG Kambli (IND),17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli,IND)
23,GS Chappell (AUS),87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell,AUS)
24,AD Nourse (SA),34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6,1935,1951,AD Nourse,SA)
25,SR Tendulkar (IND),200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69,1989,2013,SR Tendulkar,IND)
26,BC Lara (ICC/WI),131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara,ICC/WI)
27,Javed Miandad (PAK),124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48,1976,1993,Javed Miandad,PAK)
28,R Dravid (ICC/IND),164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid,ICC/IND)
29,Mohammad Yousuf (PAK),90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf,PAK)
30,Younis Khan (PAK),118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan,PAK)
31,RT Ponting (AUS),168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting,AUS)
32,J Ryder (AUS),20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3,1920,1929,J Ryder,AUS)
33,A Flower (ZIM),63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower,ZIM)
34,MEK Hussey (AUS),79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey,AUS)
35,S Chanderpaul (WI),164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul,WI)
36,SM Gavaskar (IND),125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26,1971,1987,SM Gavaskar,IND)
37,SR Waugh (AUS),168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh,AUS)
38,ML Hayden (AUS),103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden,AUS)
39,AB de Villiers (SA),114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers,SA)
40,AR Border (AUS),156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border,AUS)
41,DJ Mitchell (NZ),23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,DJ Mitchell,NZ)
42,IVA Richards (WI),121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84,1974,1991,IVA Richards,WI)
43,DCS Compton (ENG),78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3,1937,1957,DCS Compton,ENG)
44,DPMD Jayawardene (SL),149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene,SL)
45,JE Root (ENG),140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024,JE Root,ENG)
46,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq,ICC/PAK)
47,M Labuschagne (AUS),50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne,AUS)
48,FMM Worrell (WI),51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11,1948,1963,FMM Worrell,WI)
49,CP Mead (ENG),17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0,1911,1928,CP Mead,ENG)
50,V Sehwag (ICC/IND),104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag,ICC/IND)
51,Abid Ali (PAK),16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali,PAK)
52,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024,V Kohli,IND)
54,MJ Clarke (AUS),115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke,AUS)
55,KC Bland (SA),21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20,1961,1966,KC Bland,SA)
56,B Mitchell (SA),42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1,1929,1949,B Mitchell,SA)
57,Hon.FS Jackson (ENG),20,33,4,1415,144*,48.79,0,0.00,5,6,3,51,0,1893,1905,Hon.FS Jackson,ENG)
58,TT Samaraweera (SL),81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera,SL)
59,RN Harvey (AUS),79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1,1948,1963,RN Harvey,AUS)
60,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981,KD Walters,AUS)
61,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA)
62,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,WH Ponsford,AUS)
63,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,SJ McCabe,AUS)
64,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,DR Jardine,ENG)

In [34]:
df["Country"].str.split(pat = ")")

0         [AUS, ]
1         [ENG, ]
2         [AUS, ]
3          [SA, ]
4          [WI, ]
5         [ENG, ]
6         [ENG, ]
7         [ENG, ]
8          [WI, ]
9         [ENG, ]
10         [WI, ]
12         [SL, ]
13        [AUS, ]
14        [ENG, ]
16         [WI, ]
17        [ENG, ]
18     [ICC/SA, ]
19        [ENG, ]
20         [NZ, ]
21         [WI, ]
22        [IND, ]
23        [AUS, ]
24         [SA, ]
25        [IND, ]
26     [ICC/WI, ]
27        [PAK, ]
28    [ICC/IND, ]
29        [PAK, ]
30        [PAK, ]
31        [AUS, ]
32        [AUS, ]
33        [ZIM, ]
34        [AUS, ]
35         [WI, ]
36        [IND, ]
37        [AUS, ]
38        [AUS, ]
39         [SA, ]
40        [AUS, ]
41         [NZ, ]
42         [WI, ]
43        [ENG, ]
44         [SL, ]
45        [ENG, ]
46    [ICC/PAK, ]
47        [AUS, ]
48         [WI, ]
49        [ENG, ]
50    [ICC/IND, ]
51        [PAK, ]
52        [IND, ]
54        [AUS, ]
55         [SA, ]
56         [SA, ]
57        [ENG, ]
58         [SL, ]
59        [AUS, ]
60        [AUS, ]
61     [ICC/SA, ]
62        [AUS, ]
63        [AUS, ]
64        [ENG, ]
Name: Country, dtype: object

In [35]:
df["Country"] = df["Country"].str.split(pat = ")").str[0]

In [36]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Player_Name,Country
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,DG Bradman,AUS
1,HC Brook (ENG),12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,HC Brook,ENG
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,RG Pollock,SA
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954,GA Headley,WI
5,H Sutcliffe (ENG),54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6,1924,1935,H Sutcliffe,ENG
6,E Paynter (ENG),20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4,1931,1939,E Paynter,ENG
7,KF Barrington (ENG),82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27,1955,1968,KF Barrington,ENG
8,ED Weekes (WI),48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,ED Weekes,WI
9,WR Hammond (ENG),85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27,1927,1947,WR Hammond,ENG
10,GS Sobers (WI),93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974,GS Sobers,WI
12,KC Sangakkara (SL),134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara,SL
13,SPD Smith (AUS),109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith,AUS
14,JB Hobbs (ENG),61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930,JB Hobbs,ENG
16,CL Walcott (WI),44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,CL Walcott,WI
17,L Hutton (ENG),79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7,1937,1955,L Hutton,ENG
18,JH Kallis (ICC/SA),166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis,ICC/SA
19,GE Tyldesley (ENG),14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2,1921,1929,GE Tyldesley,ENG
20,KS Williamson (NZ),100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,KS Williamson,NZ
21,CA Davis (WI),15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1,1968,1973,CA Davis,WI
22,VG Kambli (IND),17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli,IND
23,GS Chappell (AUS),87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell,AUS
24,AD Nourse (SA),34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6,1935,1951,AD Nourse,SA
25,SR Tendulkar (IND),200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69,1989,2013,SR Tendulkar,IND
26,BC Lara (ICC/WI),131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara,ICC/WI
27,Javed Miandad (PAK),124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48,1976,1993,Javed Miandad,PAK
28,R Dravid (ICC/IND),164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid,ICC/IND
29,Mohammad Yousuf (PAK),90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf,PAK
30,Younis Khan (PAK),118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan,PAK
31,RT Ponting (AUS),168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting,AUS
32,J Ryder (AUS),20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3,1920,1929,J Ryder,AUS
33,A Flower (ZIM),63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower,ZIM
34,MEK Hussey (AUS),79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey,AUS
35,S Chanderpaul (WI),164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul,WI
36,SM Gavaskar (IND),125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26,1971,1987,SM Gavaskar,IND
37,SR Waugh (AUS),168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh,AUS
38,ML Hayden (AUS),103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden,AUS
39,AB de Villiers (SA),114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers,SA
40,AR Border (AUS),156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border,AUS
41,DJ Mitchell (NZ),23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,DJ Mitchell,NZ
42,IVA Richards (WI),121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84,1974,1991,IVA Richards,WI
43,DCS Compton (ENG),78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3,1937,1957,DCS Compton,ENG
44,DPMD Jayawardene (SL),149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene,SL
45,JE Root (ENG),140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024,JE Root,ENG
46,Inzamam-ul-Haq (ICC/PAK),120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq,ICC/PAK
47,M Labuschagne (AUS),50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne,AUS
48,FMM Worrell (WI),51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11,1948,1963,FMM Worrell,WI
49,CP Mead (ENG),17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0,1911,1928,CP Mead,ENG
50,V Sehwag (ICC/IND),104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag,ICC/IND
51,Abid Ali (PAK),16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali,PAK
52,V Kohli (IND),113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024,V Kohli,IND
54,MJ Clarke (AUS),115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke,AUS
55,KC Bland (SA),21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20,1961,1966,KC Bland,SA
56,B Mitchell (SA),42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1,1929,1949,B Mitchell,SA
57,Hon.FS Jackson (ENG),20,33,4,1415,144*,48.79,0,0.00,5,6,3,51,0,1893,1905,Hon.FS Jackson,ENG
58,TT Samaraweera (SL),81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera,SL
59,RN Harvey (AUS),79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1,1948,1963,RN Harvey,AUS
60,KD Walters (AUS),74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981,KD Walters,AUS
61,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA
62,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,WH Ponsford,AUS
63,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,SJ McCabe,AUS
64,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,DR Jardine,ENG

In [37]:
df = df.drop(["Player"],axis =1)

In [36]:
df

,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Player_Name,Country
0,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,DG Bradman,AUS
1,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,HC Brook,ENG
2,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS
3,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,RG Pollock,SA
4,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954,GA Headley,WI
5,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6,1924,1935,H Sutcliffe,ENG
6,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125,4,1931,1939,E Paynter,ENG
7,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591,27,1955,1968,KF Barrington,ENG
8,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,1948,1958,ED Weekes,WI
9,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419,27,1927,1947,WR Hammond,ENG
10,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974,GS Sobers,WI
11,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593,32,1954,1974,GS Sobers,WI
12,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara,SL
13,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,2010,2024,SPD Smith,AUS
14,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930,JB Hobbs,ENG
15,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276,8,1908,1930,JB Hobbs,ENG
16,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,1948,1960,CL Walcott,WI
17,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358,7,1937,1955,L Hutton,ENG
18,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis,ICC/SA
19,14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2,1921,1929,GE Tyldesley,ENG
20,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,2010,2024,KS Williamson,NZ
21,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65,1,1968,1973,CA Davis,WI
22,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli,IND
23,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell,AUS
24,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6,1935,1951,AD Nourse,SA
25,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058,69,1989,2013,SR Tendulkar,IND
26,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara,ICC/WI
27,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788,48,1976,1993,Javed Miandad,PAK
28,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid,ICC/IND
29,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf,PAK
30,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan,PAK
31,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting,AUS
32,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102,3,1920,1929,J Ryder,AUS
33,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower,ZIM
34,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey,AUS
35,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul,WI
36,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908,26,1971,1987,SM Gavaskar,IND
37,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh,AUS
38,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden,AUS
39,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers,SA
40,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border,AUS
41,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,2019,2024,DJ Mitchell,NZ
42,121,182,12,8540,291,50.23,9613+,69.77,24,45,10,952,84,1974,1991,IVA Richards,WI
43,78,131,15,5807,278,50.06,2731+,38.81,17,28,10,342,3,1937,1957,DCS Compton,ENG
44,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,DPMD Jayawardene,SL
45,140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,2012,2024,JE Root,ENG
46,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,Inzamam-ul-Haq,ICC/PAK
47,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,2018,2024,M Labuschagne,AUS
48,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11,1948,1963,FMM Worrell,WI
49,17,26,2,1185,182*,49.37,619+,30.04,4,3,3,38,0,1911,1928,CP Mead,ENG
50,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,V Sehwag,ICC/IND
51,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5,2019,2021,Abid Ali,PAK
52,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024,V Kohli,IND
53,113,191,11,8848,254*,49.15,15924,55.56,29,30,14,991,26,2011,2024,V Kohli,IND
54,115,198,22,8643,329*,49.10,15456,55.92,28,27,9,978,39,2004,2015,MJ Clarke,AUS
55,21,39,5,1669,144*,49.08,885+,37.74,3,9,2,123,20,1961,1966,KC Bland,SA
56,42,80,9,3471,189*,48.88,158+,29.11,8,21,3,41,1,1929,1949,B Mitchell,SA
57,20,33,4,1415,144*,48.79,0,0.00,5,6,3,51,0,1893,1905,Hon.FS Jackson,ENG
58,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,TT Samaraweera,SL
59,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1,1948,1963,RN Harvey,AUS
60,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,1965,1981,KD Walters,AUS
61,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,GC Smith,ICC/SA
62,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,WH Ponsford,AUS
63,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,SJ McCabe,AUS
64,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,DR Jardine,ENG

In [38]:
df.head()

,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Player_Name,Country
0,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6,1928,1948,DG Bradman,AUS
1,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,2022,2023,HC Brook,ENG
2,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges,AUS
3,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,RG Pollock,SA
4,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1,1930,1954,GA Headley,WI

In [39]:
df = df[["Player_Name","Country","Rookie_Year","Final_Year","Matches","Inns","Not_Outs","Runs","Highest_Inns_Score","Ave","Balls_Faced","Battling_Strike_Rate","100","50","0","4s","6s"]]

In [40]:
df.head()

,Player_Name,Country,Rookie_Year,Final_Year,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
0,DG Bradman,AUS,1928,1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook,ENG,2022,2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges,AUS,2015,2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock,SA,1963,1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley,WI,1930,1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104,1

In [41]:
# Change Data Types
df.dtypes

Player_Name              object
Country                  object
Rookie_Year              object
Final_Year               object
Matches                   int64
Inns                      int64
Not_Outs                  int64
Runs                      int64
Highest_Inns_Score       object
Ave                     float64
Balls_Faced              object
Battling_Strike_Rate    float64
100                       int64
50                        int64
0                         int64
4s                        int64
6s                        int64
dtype: object

In [42]:
df["Highest_Inns_Score"].str.split(pat="*").str[0]

0     334
1     186
2     269
3     274
4     270
5     194
6     243
7     256
8     207
9     336
10    365
12    319
13    239
14    211
16    220
17    364
18    224
19    122
20    251
21    183
22    227
23    247
24    231
25    248
26    400
27    280
28    270
29    223
30    313
31    257
32    201
33    232
34    195
35    203
36    236
37    200
38    380
39    278
40    205
41    190
42    291
43    278
44    374
45    254
46    329
47    215
48    261
49    182
50    319
51    215
52    254
54    329
55    144
56    189
57    144
58    231
59    205
60    250
61    277
62    266
63    232
64    127
Name: Highest_Inns_Score, dtype: object

In [43]:
df["Highest_Inns_Score"]=df["Highest_Inns_Score"].str.split(pat="*").str[0]

In [44]:
df.head()

,Player_Name,Country,Rookie_Year,Final_Year,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
0,DG Bradman,AUS,1928,1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626,6
1,HC Brook,ENG,2022,2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges,AUS,2015,2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock,SA,1963,1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley,WI,1930,1954,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104,1

In [45]:
# set the appropriate data type
df["Highest_Inns_Score"] = df["Highest_Inns_Score"].astype("int")

In [46]:
df.dtypes

Player_Name              object
Country                  object
Rookie_Year              object
Final_Year               object
Matches                   int64
Inns                      int64
Not_Outs                  int64
Runs                      int64
Highest_Inns_Score        int32
Ave                     float64
Balls_Faced              object
Battling_Strike_Rate    float64
100                       int64
50                        int64
0                         int64
4s                        int64
6s                        int64
dtype: object

In [47]:
## QUESTION SEE IF YOU CAN FIX Rookie Year and Final Year
# Set multiple data type in one syntax

df = df.astype({"Rookie_Year":"int","Final_Year":"int"})

In [48]:
df["Balls_Faced"] = df["Balls_Faced"].str.split(pat = "+").str[0]

In [49]:
df.head()

,Player_Name,Country,Rookie_Year,Final_Year,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
0,DG Bradman,AUS,1928,1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6
1,HC Brook,ENG,2022,2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges,AUS,2015,2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock,SA,1963,1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11
4,GA Headley,WI,1930,1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1

In [50]:
df.dtypes

Player_Name              object
Country                  object
Rookie_Year               int32
Final_Year                int32
Matches                   int64
Inns                      int64
Not_Outs                  int64
Runs                      int64
Highest_Inns_Score        int32
Ave                     float64
Balls_Faced              object
Battling_Strike_Rate    float64
100                       int64
50                        int64
0                         int64
4s                        int64
6s                        int64
dtype: object

In [51]:
df["Balls_Faced"]

0      9800
1      1287
2      2667
3      1707
4       416
5      6558
6      1288
7      4957
8       NaN
9      7491
10     4063
12    22882
13    18100
14     5363
16      NaN
17     2844
18    28903
19      178
20    17006
21      665
22     1823
23    13079
24      108
25    29437
26    19753
27    15164
28    31258
29    14372
30    19375
31    22782
32     2035
33    10636
34    12436
35    27395
36    14184
37    22461
38    14349
39    16077
40    27002
41     3014
42     9613
43     2731
44    22959
45    20762
46    16345
47     7809
48      488
49      619
50    10441
51     2445
52    15924
54    15456
55      885
56      158
57      NaN
58    11641
59     1799
60     8662
61    15525
62     3118
63     3217
64     2110
Name: Balls_Faced, dtype: object

In [52]:
df["Balls_Faced"] = df["Balls_Faced"].fillna(0)

In [53]:
df["Balls_Faced"]

0      9800
1      1287
2      2667
3      1707
4       416
5      6558
6      1288
7      4957
8         0
9      7491
10     4063
12    22882
13    18100
14     5363
16        0
17     2844
18    28903
19      178
20    17006
21      665
22     1823
23    13079
24      108
25    29437
26    19753
27    15164
28    31258
29    14372
30    19375
31    22782
32     2035
33    10636
34    12436
35    27395
36    14184
37    22461
38    14349
39    16077
40    27002
41     3014
42     9613
43     2731
44    22959
45    20762
46    16345
47     7809
48      488
49      619
50    10441
51     2445
52    15924
54    15456
55      885
56      158
57        0
58    11641
59     1799
60     8662
61    15525
62     3118
63     3217
64     2110
Name: Balls_Faced, dtype: object

In [54]:
df["Balls_Faced"] = df["Balls_Faced"].astype("int")

In [55]:
df["Matches"]= df["Matches"].astype("int")

In [56]:
df.dtypes

Player_Name              object
Country                  object
Rookie_Year               int32
Final_Year                int32
Matches                   int32
Inns                      int64
Not_Outs                  int64
Runs                      int64
Highest_Inns_Score        int32
Ave                     float64
Balls_Faced               int32
Battling_Strike_Rate    float64
100                       int64
50                        int64
0                         int64
4s                        int64
6s                        int64
dtype: object

In [57]:
df.head(5)     # - semua data types dah ubah

,Player_Name,Country,Rookie_Year,Final_Year,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s
0,DG Bradman,AUS,1928,1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6
1,HC Brook,ENG,2022,2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23
2,AC Voges,AUS,2015,2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock,SA,1963,1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11
4,GA Headley,WI,1930,1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1

In [58]:
# Build Out Career_Length
df["Career_Length"] = df["Final_Year"] - df["Rookie_Year"]
df["Career_Length"]

0     20
1      1
2      1
3      7
4     24
5     11
6      8
7     13
8     10
9     20
10    20
12    15
13    14
14    22
16    12
17    18
18    18
19     8
20    14
21     5
22     2
23    14
24    16
25    24
26    16
27    17
28    16
29    12
30    17
31    17
32     9
33    10
34     8
35    21
36    16
37    19
38    15
39    14
40    16
41     5
42    17
43    20
44    17
45    12
46    15
47     6
48    15
49    17
50    12
51     2
52    13
54    11
55     5
56    20
57    12
58    12
59    15
60    16
61    12
62    10
63     8
64     6
Name: Career_Length, dtype: int32

# Calculations

In [59]:
#1. What is the Average Career Lenghth

df["Career_Length"].mean()

13.193548387096774

In [60]:
#2. AVG Batting Strike Rate for Cricketers Who played over 10 years
df[df["Career_Length"] >10]["Battling_Strike_Rate"].mean()

47.94681818181819

In [ ]:
#3. Find cricketers who played before 1960

In [61]:
df[df["Rookie_Year"] < 1960]["Player_Name"].count()

23

In [62]:
#4. Max Highest Inns Score by Country

df.groupby("Country")["Highest_Inns_Score"].max().to_frame("HihghInnCountry").reset_index().sort_values("HihghInnCountry",ascending = False)

    Country  HihghInnCountry
5    ICC/WI              400
0       AUS              380
10       SL              374
11       WI              365
1       ENG              364
3   ICC/PAK              329
2   ICC/IND              319
8       PAK              313
9        SA              278
4    ICC/SA              277
6       IND              254
7        NZ              251
12      ZIM              232

In [63]:
#5. Hundreds, Fifties, ducks (0) AVG by Country
df.groupby("Country")[["100","50","0"]].mean()

               100         50          0
Country
AUS      20.625000  28.375000   8.562500
ENG      12.384615  20.846154   4.307692
ICC/IND  29.500000  47.500000  12.000000
ICC/PAK  25.000000  46.000000  15.000000
ICC/SA   36.000000  48.000000  13.500000
ICC/WI   34.000000  48.000000  17.000000
IND      29.500000  36.500000  10.750000
NZ       18.500000  22.000000   6.000000
PAK      21.250000  28.000000   9.500000
SA        9.800000  20.200000   3.400000
SL       28.666667  44.000000  12.333333
WI       16.625000  25.625000   7.250000
ZIM      12.000000  27.000000   5.000000

In [64]:
df.head(5)

,Player_Name,Country,Rookie_Year,Final_Year,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Career_Length
0,DG Bradman,AUS,1928,1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,20
1,HC Brook,ENG,2022,2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,1
2,AC Voges,AUS,2015,2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,1
3,RG Pollock,SA,1963,1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,7
4,GA Headley,WI,1930,1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,24

In [65]:
df

,Player_Name,Country,Rookie_Year,Final_Year,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Battling_Strike_Rate,100,50,0,4s,6s,Career_Length
0,DG Bradman,AUS,1928,1948,52,80,10,6996,334,99.94,9800,58.60,29,13,7,626,6,20
1,HC Brook,ENG,2022,2023,12,20,1,1181,186,62.15,1287,91.76,4,7,1,141,23,1
2,AC Voges,AUS,2015,2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,1
3,RG Pollock,SA,1963,1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,7
4,GA Headley,WI,1930,1954,22,40,4,2190,270,60.83,416,56.00,10,5,2,104,1,24
5,H Sutcliffe,ENG,1924,1935,54,84,9,4555,194,60.73,6558,34.59,16,23,2,202,6,11
6,E Paynter,ENG,1931,1939,20,31,5,1540,243,59.23,1288,45.88,4,7,3,125,4,8
7,KF Barrington,ENG,1955,1968,82,131,15,6806,256,58.67,4957,42.42,20,35,5,591,27,13
8,ED Weekes,WI,1948,1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258,2,10
9,WR Hammond,ENG,1927,1947,85,140,16,7249,336,58.45,7491,38.07,22,24,4,419,27,20
10,GS Sobers,WI,1954,1974,93,160,21,8032,365,57.78,4063,53.58,26,30,12,593,32,20
12,KC Sangakkara,SL,2000,2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,15
13,SPD Smith,AUS,2010,2024,109,195,25,9685,239,56.97,18100,53.50,32,41,10,1063,54,14
14,JB Hobbs,ENG,1908,1930,61,102,7,5410,211,56.94,5363,46.22,15,28,4,276,8,22
16,CL Walcott,WI,1948,1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107,11,12
17,L Hutton,ENG,1937,1955,79,138,15,6971,364,56.67,2844,39.34,19,33,5,358,7,18
18,JH Kallis,ICC/SA,1995,2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,18
19,GE Tyldesley,ENG,1921,1929,14,20,2,990,122,55.00,178,29.21,3,6,2,37,2,8
20,KS Williamson,NZ,2010,2024,100,176,17,8743,251,54.98,17006,51.41,32,34,11,971,24,14
21,CA Davis,WI,1968,1973,15,29,5,1301,183,54.20,665,35.48,4,4,1,65,1,5
22,VG Kambli,IND,1993,1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,2
23,GS Chappell,AUS,1970,1984,87,151,19,7110,247,53.86,13079,51.53,24,31,12,755,16,14
24,AD Nourse,SA,1935,1951,34,62,7,2960,231,53.81,108,63.88,9,14,3,115,6,16
25,SR Tendulkar,IND,1989,2013,200,329,33,15921,248,53.78,29437,54.04,51,68,14,2058,69,24
26,BC Lara,ICC/WI,1990,2006,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,16
27,Javed Miandad,PAK,1976,1993,124,189,21,8832,280,52.57,15164,45.99,23,43,6,788,48,17
28,R Dravid,ICC/IND,1996,2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,16
29,Mohammad Yousuf,PAK,1998,2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,12
30,Younis Khan,PAK,2000,2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,17
31,RT Ponting,AUS,1995,2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,17
32,J Ryder,AUS,1920,1929,20,32,5,1394,201,51.62,2035,44.86,3,9,1,102,3,9
33,A Flower,ZIM,1992,2002,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,10
34,MEK Hussey,AUS,2005,2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,8
35,S Chanderpaul,WI,1994,2015,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,21
36,SM Gavaskar,IND,1971,1987,125,214,16,10122,236,51.12,14184,43.35,34,45,12,908,26,16
37,SR Waugh,AUS,1985,2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,19
38,ML Hayden,AUS,1994,2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,15
39,AB de Villiers,SA,2004,2018,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,14
40,AR Border,AUS,1978,1994,156,265,44,11174,205,50.56,27002,41.09,27,63,11,1161,28,16
41,DJ Mitchell,NZ,2019,2024,23,37,5,1608,190,50.25,3014,53.35,5,10,1,158,29,5
42,IVA Richards,WI,1974,1991,121,182,12,8540,291,50.23,9613,69.77,24,45,10,952,84,17
43,DCS Compton,ENG,1937,1957,78,131,15,5807,278,50.06,2731,38.81,17,28,10,342,3,20
44,DPMD Jayawardene,SL,1997,2014,149,252,15,11814,374,49.84,22959,51.45,34,50,15,1387,61,17
45,JE Root,ENG,2012,2024,140,257,21,11736,254,49.72,20762,56.52,31,61,12,1280,44,12
46,Inzamam-ul-Haq,ICC/PAK,1992,2007,120,200,22,8830,329,49.60,16345,54.02,25,46,15,1105,48,15
47,M Labuschagne,AUS,2018,2024,50,90,7,4114,215,49.56,7809,52.68,11,20,4,463,12,6
48,FMM Worrell,WI,1948,1963,51,87,9,3860,261,49.48,488,40.16,9,22,11,240,11,15
49,CP Mead,ENG,1911,1928,17,26,2,1185,182,49.37,619,30.04,4,3,3,38,0,17
50,V Sehwag,ICC/IND,2001,2013,104,180,6,8586,319,49.34,10441,82.23,23,32,16,1233,91,12
51,Abid Ali,PAK,2019,2021,16,26,2,1180,215,49.16,2445,48.26,4,3,2,148,5,2
52,V Kohli,IND,2011,2024,113,191,11,8848,254,49.15,15924,55.56,29,30,14,991,26,13
54,MJ Clarke,AUS,2004,2015,115,198,22,8643,329,49.10,15456,55.92,28,27,9,978,39,11
55,KC Bland,SA,1961,1966,21,39,5,1669,144,49.08,885,37.74,3,9,2,123,20,5
56,B Mitchell,SA,1929,1949,42,80,9,3471,189,48.88,158,29.11,8,21,3,41,1,20
57,Hon.FS Jackson,ENG,1893,1905,20,33,4,1415,144,48.79,0,0.00,5,6,3,51,0,12
58,TT Samaraweera,SL,2001,2013,81,132,20,5462,231,48.76,11641,46.92,14,30,11,633,7,12
59,RN Harvey,AUS,1948,1963,79,137,10,6149,205,48.41,1799,43.74,21,24,7,427,1,15
60,KD Walters,AUS,1965,1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,16
61,GC Smith,ICC/SA,2002,2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,12
62,WH Ponsford,AUS,1924,1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,10
63,SJ McCabe,AUS,1930,1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,8
64,DR Jardine,ENG,1928,1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,6

In [67]:
# saving file to excel

df.to_excel('Cleaned_Cricket_Test_match_data.xlsx', index = False)

In [69]:
# saving file to csv

df.to_csv('Cleaned_Cricket_Test_Match_Data.csv', index = False)